name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application.yml
      run: |
        mkdir -p ./src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

    - name: Make firebase.json
      run: |
        mkdir -p ./src/main/resources/firebase
        echo "${{ secrets.FIREBASE_JSON }}" > ./src/main/resources/firebase/remind-me-firebase.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Extract version from gradle.properties
      id: extract_version
      run: |
        VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
        echo "::set-output name=VERSION::$VERSION"

    - name: DockerHub Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker image Build
      run:
        VERSION=${{ steps.extract_version.outputs.VERSION }}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:$VERSION .

    - name: DockerHub push
      run:
        VERSION=${{ steps.extract_version.outputs.VERSION }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}:$VERSION
      

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          
          script: |
            docker-compose up -d
            docker image prune -a -f
